server:
  port: 8080

spring:
  application:
    name: researcher
  datasource:
    url: jdbc:postgresql://localhost:5432/shopme
    username: postgres
    password: password
  data:
    jpa:
      repositories:
        enabled: true